@Shop.API_HostAddress = https://localhost:7034

POST {{Shop.API_HostAddress}}/SubCategories
Content-Type: application/json
{
   
}

###

PATCH {{Shop.API_HostAddress}}/SubCategories/30
Content-Type: application/json

{
  "id" : 30,
  "name": "Test000",
  "categoryId": 10
}

###
